// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/sync-encore-overrides.py; do not edit by hand.
// Source: niakw/encore-overrides@0afb14f3c148b19111f15a4f2416bb4590b0edc3
#pragma once
#include <array>
#include <cstdint>
namespace Eden::EncoreOverrides {
struct VideoProfile { int renderer; int output; int resolution; int filter; int fsr_sharpness; int anti_aliasing; int refresh; bool docked; };
inline constexpr int kAuthoredProfileCount = 4;
inline constexpr int kCustomProfile = 4;
inline constexpr const char* kSourceRevision = "0afb14f3c148b19111f15a4f2416bb4590b0edc3";
inline constexpr int kDatabaseRevision = 6;
inline constexpr std::array<VideoProfile, kAuthoredProfileCount> kGeneralProfiles = {{
    {1, 0, 3, 0, 50, 0, 0, true},
    {1, 1, 4, 0, 50, 1, 0, true},
    {1, 2, 5, 2, 50, 1, 0, true},
    {1, 2, 6, 0, 50, 0, 0, true},
}};
struct TitleProfiles { std::uint64_t title_id; std::array<VideoProfile, kAuthoredProfileCount> profiles; };
inline constexpr std::array<TitleProfiles, 1> kTitleProfiles = {{
    // EA SPORTS FC 27
    {0x0100C49025D3E000ULL, {{
        {1, 0, 2, 1, 40, 0, 0, true},
        {1, 1, 4, 0, 50, 1, 0, true},
        {1, 1, 5, 0, 50, 1, 0, true},
        {1, 2, 6, 0, 50, 0, 0, true},
    }}}},
}};
inline constexpr int ClampTier(int tier) { return tier < 0 ? 0 : tier >= kAuthoredProfileCount ? kAuthoredProfileCount - 1 : tier; }
inline constexpr const VideoProfile& GeneralProfile(int tier) { return kGeneralProfiles[static_cast<std::size_t>(ClampTier(tier))]; }
inline constexpr const VideoProfile& ProfileForTitle(std::uint64_t title_id, int tier) {
    for (const auto& entry : kTitleProfiles) if (entry.title_id == title_id) return entry.profiles[static_cast<std::size_t>(ClampTier(tier))];
    return GeneralProfile(tier);
}
inline constexpr bool HasSpecificProfile(std::uint64_t title_id) {
    for (const auto& entry : kTitleProfiles) if (entry.title_id == title_id) return true;
    return false;
}
} // namespace Eden::EncoreOverrides
