// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/sync-glyph-overrides.py from niakw/encore-overrides/glyphs/manifest.json.
// Do not hand-edit. Rules select ART assets only; input mapping is unrelated.
#pragma once
#include <array>
#include <cstdint>
namespace Eden::GlyphOverridesGenerated {
struct Rule { std::uint64_t title; const char* update_version; const char* build_id; };
inline constexpr int kRevision = 1;
inline constexpr std::array<Rule, 0> kRules = {{
}};
} // namespace Eden::GlyphOverridesGenerated
