#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Prevent one-past-end sparse GPU/CPU table access at the PS5 2-MiB slot boundary.

The derived header is generated by headless/CMakeLists.txt from the EXACT
upstream pinned source. This validation has no PS5 toolchain requirement.
"""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
cmake = (root / "headless/CMakeLists.txt").read_text()
old = 'if (index > alloc_size / sizeof(T)) {'
new = 'if (index >= alloc_size / sizeof(T)) {'
assert 'eden_sparse_replace("' + old + '"' in cmake
assert '"' + new + '" 3)' in cmake
# Both the condition and its replacement are validated by eden_sparse_replace
# at CMake configuration: exactly three old matches are required.
for capacity in (1, 2, 4096, 1 << 20):
    assert all(index < capacity for index in (0, capacity - 1))
    assert all(index >= capacity for index in (capacity, capacity + 1))
print("PASS: pinned SparseLargeVector GetAndFault/Set/IsCommittedPage stop at count")
