#!/usr/bin/env python3
"""Statically verify generic account/BSD/address HLE patches for every game.

Does NOT build, link, invoke CI or change the pinned Eden source/cache.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
from tempfile import TemporaryDirectory

ROOT = Path(__file__).resolve().parents[1]
PIN = (ROOT / '.local/headless-cache').read_text().strip() if (ROOT / '.local/headless-cache').exists() else ''
PATCH = ROOT / 'headless/backports/eden-fc27-hle-compat.patch'
assert PATCH.is_file()
source = Path(PIN) / 'source' if PIN else None
if source is None or not (source / 'GIT-COMMIT').exists():
    print('Universal HLE patch static markers only (no local pinned Eden source)')
    s = PATCH.read_text()
    for term in ('LoadOpenContext', 'Ioctl', 'guest_addrin.len', 'Errno::INVAL'):
        assert term in s, term
    assert s.count('+    write_buffer.resize(guest_addrin.len);') == 2
    # No `GetSockNameImpl` declaration is added by the patch: it modifies the
    # two existing handlers. Earlier CI incorrectly required this absent marker.
    print('Universal account/BSD/sockaddr patch markers: PASS')
    sys.exit(0)
assert (source / 'GIT-COMMIT').read_text().strip() == '5f142c7926d0c7fcbbd0ce30794d72f638a43b2a'
need = ('src/core/hle/service/acc/acc.h', 'src/core/hle/service/acc/acc.cpp',
        'src/core/hle/service/sockets/bsd.h', 'src/core/hle/service/sockets/bsd.cpp')
with TemporaryDirectory(prefix='encore-fc27-hle-') as temp:
    t = Path(temp)
    for rel in need:
        dest = t / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source / rel, dest)
    subprocess.run(['git', 'apply', '--check', str(PATCH)], cwd=t, check=True)
    subprocess.run(['git', 'apply', str(PATCH)], cwd=t, check=True)
    acc = (t / need[1]).read_text()
    bsd = (t / need[3]).read_text()
    assert '{130, &ACC_U0::LoadOpenContext, "LoadOpenContext"}' in acc
    assert '{19, &BSD_USA::Ioctl, "Ioctl"}' in bsd
    assert bsd.count('write_buffer.resize(guest_addrin.len);') == 2
    for rel in (need[1], need[3]):
        assert (t / rel).stat().st_size > 0
    print('FC27 HLE pinned-source patch dry-run: 4/4 files PASS')
    if '--syntax' not in sys.argv:
        sys.exit(0)
    db = Path(PIN) / 'native-local/compile_commands.json'
    assert db.is_file(), f'Native compile DB unavailable: {db}'
    entries = json.loads(db.read_text())
    compiled = 0
    for rel in (need[1], need[3]):
        match = [entry for entry in entries if entry['file'].endswith('/' + rel)]
        assert len(match) == 1, (rel, len(match))
        cmd = shlex.split(match[0]['command'])
        filename = match[0]['file']
        assert cmd[0].endswith('clang++') or cmd[0].endswith('clang++-18'), cmd[0]
        opts=[]
        i=1
        while i < len(cmd):
            part=cmd[i]
            if part in ('-o','-MF','-MT','-MQ'):
                i+=2; continue
            if part in ('-c', '-MD', '-MMD', '-MP'):
                i+=1;continue
            if part == filename:
                i+=1;continue
            opts.append(part)
            i+=1
        args = [cmd[0], '-fsyntax-only', '-Werror', '-I' + str(t / 'src')]
        # Native DB was generated by an older CMake/LLVM combination. Its
        # '-Wno-error-all' is not an LLVM 18 warning group. Drop only that
        # unsupported compatibility flag; keep all PS5 target and include flags.
        args.extend(x for x in opts if x != '-Wno-error-all')
        args.append(str(t / rel))
        env = os.environ.copy()
        env.setdefault('SDKROOT', '/Library/Developer/CommandLineTools/SDKs/MacOSX26.5.sdk')
        print('Checking PS5 C++ syntax:',rel, flush=True)
        subprocess.run(args, cwd=match[0]['directory'], env=env, check=True)
        compiled+=1
    print(f'FC27 HLE PS5 compiler syntax: {compiled}/{compiled} PASS (no build/link)')
