#!/usr/bin/env python3
"""Sync the visual-button glyph catalogue from niakw/encore-overrides.

Like tools/sync-encore-overrides.py, this embeds a verified offline snapshot.
No textures, no unlicensed game images, no controller remapping.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

HEX_TITLE = re.compile(r"[0-9a-fA-F]{16}\Z")
HEX_BUILD = re.compile(r"(?:[0-9a-fA-F]{40}|[0-9a-fA-F]{64})\Z")
UPDATE = re.compile(r"[a-zA-Z0-9_.+ -]{1,64}\Z")


def make_snapshot(src: Path) -> tuple[str, str]:
    data = json.loads(src.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or set(data) != {"schema_version", "revision", "titles"}:
        raise ValueError("invalid glyph catalogue schema")
    if type(data["schema_version"]) is not int or data["schema_version"] != 1:
        raise ValueError("unknown glyph catalogue version")
    if type(data["revision"]) is not int or not 1 <= data["revision"] <= 2**31 - 1:
        raise ValueError("invalid glyph catalogue revision")
    if not isinstance(data["titles"], list) or len(data["titles"]) > 256:
        raise ValueError("glyph title rules exceed 256")
    normalized = []
    seen = set()
    for entry in data["titles"]:
        if not isinstance(entry, dict) or set(entry) != {"title_id", "update_version", "build_id"}:
            raise ValueError("each glyph rule needs title_id, update_version and build_id only")
        title = entry["title_id"]
        version = entry["update_version"]
        build = entry["build_id"]
        if not isinstance(title, str) or HEX_TITLE.fullmatch(title) is None or int(title, 16) == 0:
            raise ValueError("invalid title ID")
        if not isinstance(version, str) or UPDATE.fullmatch(version) is None:
            raise ValueError("invalid update version")
        if not isinstance(build, str) or HEX_BUILD.fullmatch(build) is None:
            raise ValueError("invalid build ID")
        key = (title.upper(), version)
        if key in seen:
            raise ValueError("duplicate title+update version")
        seen.add(key)
        normalized.append({"title_id": title.upper(), "update_version": version,
                           "build_id": build.upper()})
    normalized.sort(key=lambda x: (x["title_id"], x["update_version"]))
    canonical = {"schema_version": 1, "revision": data["revision"], "titles": normalized}
    snapshot = json.dumps(canonical, indent=2, ensure_ascii=True) + "\n"
    rows = []
    for item in normalized:
        rows.append(f'    {{0x{item["title_id"]}ULL, '
                    f'{json.dumps(item["update_version"])}, '
                    f'{json.dumps(item["build_id"]})}},')
    code = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/sync-glyph-overrides.py from niakw/encore-overrides/glyphs/manifest.json.",
        "// Do not hand-edit. Rules select ART assets only; input mapping is unrelated.",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "namespace Eden::GlyphOverridesGenerated {",
        "struct Rule { std::uint64_t title; const char* update_version; const char* build_id; };",
        f"inline constexpr int kRevision = {data['revision']};",
        f"inline constexpr std::array<Rule, {len(rows)}> kRules = {{{{",
        *rows,
        "}};",
        "} // namespace Eden::GlyphOverridesGenerated",
        "",
    ]
    return snapshot, "\n".join(code)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--source", type=Path, help="checkout of niakw/encore-overrides")
    p.add_argument("--manifest", type=Path,
                   help="already synced manifest; for offline reproducibility tests")
    p.add_argument("--output", type=Path,
                   default=Path("headless/glyph_overrides_generated.h"))
    p.add_argument("--snapshot", type=Path,
                   default=Path("data/glyph-overrides.json"))
    p.add_argument("--check", action="store_true",
                   help="read-only: fail if generated output or snapshot drifted")
    args = p.parse_args()
    if (args.source is None) == (args.manifest is None):
        p.error("pass exactly one of --source or --manifest")
    source = args.source / "glyphs" / "manifest.json" if args.source else args.manifest
    snapshot, header = make_snapshot(source)
    if args.check:
        if args.snapshot.read_text() != snapshot or args.output.read_text() != header:
            raise SystemExit("glyph overrides generated C++ or local snapshot is stale")
    else:
        args.snapshot.parent.mkdir(parents=True, exist_ok=True)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.snapshot.write_text(snapshot)
        args.output.write_text(header)
    print(f"PASS glyph visual overrides: {source}, sync/check={args.check}")


if __name__ == "__main__":
    main()
