#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, subprocess, sys
from pathlib import Path

PROFILE_IDS = ("minimum", "recommended", "high", "ultra")
RENDERER = {"opengl": 0, "vulkan": 1}
OUTPUT = {"1080p": 0, "1440p": 1, "2160p": 2}
RESOLUTION = {0.25: 0, 0.5: 1, 0.75: 2, 1.0: 3, 1.25: 4, 1.5: 5, 2.0: 6, 3.0: 7, 4.0: 8}
FILTER = {"bilinear": 0, "fsr": 1, "bicubic": 2, "nearest": 3}
AA = {"none": 0, "fxaa": 1, "smaa": 2}
REFRESH = {60: 0, 120: 1}

def profile(settings: dict) -> tuple[int,int,int,int,int,int,int,bool]:
    return (
        RENDERER[settings["renderer"]],
        OUTPUT[settings["tv_output"]],
        RESOLUTION[float(settings["game_resolution"])],
        FILTER[settings["upscaling_filter"]],
        int(settings["fsr_sharpness"]),
        AA[settings["anti_aliasing"]],
        REFRESH[int(settings["refresh_rate_hz"])],
        settings.get("console_mode", "docked") != "handheld",
    )

def cpp_profile(p: tuple[int,int,int,int,int,int,int,bool]) -> str:
    return "{" + ", ".join(map(str, p[:-1])) + ", " + ("true" if p[-1] else "false") + "}"

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, required=True, help="checkout of niakw/encore-overrides")
    ap.add_argument("--output", type=Path, default=Path("headless/encore_overrides_generated.h"))
    args = ap.parse_args()
    source = args.source.resolve()
    manifest = json.loads((source / "manifest.json").read_text())
    database_revision = int(manifest.get("database_revision", 0))
    general = {pid: json.loads((source / "general" / f"{pid}.json").read_text())["settings"] for pid in PROFILE_IDS}
    general_cpp = [profile(general[pid]) for pid in PROFILE_IDS]
    controls = json.loads((source / "general" / "controls.json").read_text())
    detection = controls["detection"]
    gameplay = detection["gameplay"]
    ui = detection["ui"]
    control_cpp = (
        f'{float(gameplay["stick_threshold"]):.2f}f',
        int(gameplay["trigger_threshold_raw"]),
        int(gameplay["evidence_enter"]),
        int(gameplay["evidence_per_active_poll"]),
        f'{float(ui["quiet_stick_threshold"]):.2f}f',
        int(ui["quiet_polls_before_dpad"]),
        int(ui["menu_evidence_enter"]),
        int(ui["options_touchpad_weight"]),
        int(ui["dpad_weight"]),
        bool(detection.get("hysteresis", True)),
    )
    specifics: list[tuple[int,str,list[tuple[int,int,int,int,int,int,int,bool]]]] = []
    for path in sorted((source / "games").glob("*.json")):
        data = json.loads(path.read_text())
        profiles = data.get("profiles", {})
        if not all(pid in profiles and "settings" in profiles[pid] for pid in PROFILE_IDS):
            continue
        values = [profile(profiles[pid]["settings"]) for pid in PROFILE_IDS]
        if any(profiles[pid]["settings"] != general[pid] for pid in PROFILE_IDS):
            specifics.append((int(data["title_id"], 16), data.get("name", path.stem), values))
    try:
        revision = subprocess.check_output(["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        revision = "unknown"
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/sync-encore-overrides.py; do not edit by hand.",
        f"// Source: niakw/encore-overrides@{revision}",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "namespace Eden::EncoreOverrides {",
        "struct AutoControlProfile { float gameplay_stick_threshold; int trigger_threshold_raw; unsigned gameplay_evidence_enter; unsigned gameplay_evidence_per_active_poll; float quiet_stick_threshold; unsigned quiet_polls_before_dpad; unsigned menu_evidence_enter; unsigned options_touchpad_weight; unsigned dpad_weight; bool hysteresis; };",
        "struct VideoProfile { int renderer; int output; int resolution; int filter; int fsr_sharpness; int anti_aliasing; int refresh; bool docked; };",
        "inline constexpr int kAuthoredProfileCount = 4;",
        "inline constexpr int kCustomProfile = 4;",
        f'inline constexpr const char* kSourceRevision = "{revision}";',
        f"inline constexpr int kDatabaseRevision = {database_revision};",
        "inline constexpr AutoControlProfile kPlayStationAutoControls{"
            + ", ".join(map(str, control_cpp[:-1]))
            + ", " + ("true" if control_cpp[-1] else "false") + "};",
        "inline constexpr std::array<VideoProfile, kAuthoredProfileCount> kGeneralProfiles = {{",
    ]
    for p in general_cpp:
        lines.append(f"    {cpp_profile(p)},")
    lines += ["}};", "struct TitleProfiles { std::uint64_t title_id; std::array<VideoProfile, kAuthoredProfileCount> profiles; };",
              f"inline constexpr std::array<TitleProfiles, {len(specifics)}> kTitleProfiles = {{{{"]
    for title, name, values in specifics:
        safe = name.replace("*/", "* /")
        lines.append(f"    // {safe}")
        lines.append(f"    {{0x{title:016X}ULL, {{{{")
        for p in values:
            lines.append(f"        {cpp_profile(p)},")
        lines.append("    }}},")
    lines += [
        "}};",
        "inline constexpr int ClampTier(int tier) { return tier < 0 ? 0 : tier >= kAuthoredProfileCount ? kAuthoredProfileCount - 1 : tier; }",
        "inline constexpr const VideoProfile& GeneralProfile(int tier) { return kGeneralProfiles[static_cast<std::size_t>(ClampTier(tier))]; }",
        "inline constexpr const VideoProfile& ProfileForTitle(std::uint64_t title_id, int tier) {",
        "    for (const auto& entry : kTitleProfiles) if (entry.title_id == title_id) return entry.profiles[static_cast<std::size_t>(ClampTier(tier))];",
        "    return GeneralProfile(tier);",
        "}",
        "inline constexpr bool HasSpecificProfile(std::uint64_t title_id) {",
        "    for (const auto& entry : kTitleProfiles) if (entry.title_id == title_id) return true;",
        "    return false;",
        "}",
        "} // namespace Eden::EncoreOverrides",
        "",
    ]
    args.output.write_text("\n".join(lines))
    print(f"generated {args.output}: revision={database_revision} general={len(general_cpp)} specific={len(specifics)} source={revision}")
    # The default Encore snapshot sync now also captures curated visual
    # button-art rules. Custom --output fixture runs remain untouched.
    if args.output == Path("headless/encore_overrides_generated.h") and (
        source / "glyphs" / "manifest.json").is_file():
        subprocess.run([sys.executable, "-B",
                        str(Path(__file__).with_name("sync-glyph-overrides.py")),
                        "--source", str(source)], check=True)

if __name__ == "__main__":
    main()
